# Site settings
course_name: Software Engineering
course_description: "This course on Software Engineering aims to prepare under-grad studnets a professional carrer in software industry"
course_semester: "ODD 2022"

baseurl: "/SE-2022-Final" # the subpath of your site, e.g. /blog/
url: "http://akiwele.github.io/" # the base hostname & protocol for your site

schoolname: "Dr Babasaheb Ambedkar Technological University"
schoolurl: "https://dbatu.ac.in"
twitter_username: akiwelekar

address: |
    Dr Babasaheb Ambedkar Technological University
    Lonere 402103 Raigad Maharashtra
    India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
